import '../models/course_model.dart';

class CourseRepository {
  Future<List<CourseModel>> fetchCourses() async {
    await Future.delayed(const Duration(milliseconds: 500));
    
    return [
      CourseModel(
        id: '1',
        title: "React Avancé - Les Hooks et Context API",
        description: "Maîtrisez React avec les Hooks modernes, Context API et Redux. Développez des applications complexes avec les meilleures pratiques.",
        price: 89.0,
        originalPrice: 129.0,
        category: "Développement",
        image: "https://miro.medium.com/v2/resize:fit:1200/1*y6C4nSvy2Woe0m7bWEn4BA.png",
        instructor: "Ahmed Ben Ali",
        rating: 4.8,
        students: 1240,
        duration: "12h 30min",
        level: "Intermédiaire",
        discountPercentage: 31,
      ),
      CourseModel(
        id: '2',
        title: "UI/UX Design avec Figma",
        description: "Apprenez à créer des interfaces utilisateur modernes et intuitives. Prototypage avancé et design system.",
        price: 69.0,
        originalPrice: 99.0,
        category: "Design",
        image: "https://s3-alpha.figma.com/hub/file/1166690750/85f69649-5387-44c2-ba45-81f1383d7945-cover.png",
        instructor: "Sarah Trabelsi",
        rating: 4.9,
        students: 890,
        duration: "8h 15min",
        level: "Débutant",
        discountPercentage: 30,
      ),
      CourseModel(
        id: '3',
        title: "Marketing Digital 2024",
        description: "Stratégies complètes de marketing digital: SEO, réseaux sociaux, email marketing et analytics.",
        price: 79.0,
        originalPrice: 119.0,
        category: "Business",
        image: "https://img.freepik.com/free-photo/digital-marketing-with-icons-business-people_53876-94833.jpg",
        instructor: "Mohamed Dridi",
        rating: 4.7,
        students: 1560,
        duration: "10h 45min",
        level: "Tous niveaux",
        discountPercentage: 34,
      ),
      CourseModel(
        id: '4',
        title: "Python & Data Science",
        description: "Devenez data scientist avec Python. Pandas, NumPy, Matplotlib et machine learning.",
        price: 99.0,
        originalPrice: 149.0,
        category: "Développement",
        image: "https://imageio.forbes.com/specials-images/imageserve/5e5d657927d370000737e362/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
        instructor: "Leila Mansour",
        rating: 4.8,
        students: 2100,
        duration: "15h 20min",
        level: "Avancé",
        discountPercentage: 34,
      ),
      CourseModel(
        id: '5',
        title: "Adobe Photoshop Pro",
        description: "Maîtrisez Photoshop de A à Z. Retouche photo, montage avancé et création digitale.",
        price: 59.0,
        originalPrice: 89.0,
        category: "Design",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcCAXyMfbKxG-KMgXQnKwcR4n6qV8j8a8XFg&s",
        instructor: "Youssef Guedira",
        rating: 4.6,
        students: 750,
        duration: "9h 10min",
        level: "Débutant",
        discountPercentage: 34,
      ),
      CourseModel(
        id: '6',
        title: "Gestion de Projet Agile",
        description: "Méthodologies Agile, Scrum, Kanban. Devenez chef de projet certifié.",
        price: 85.0,
        originalPrice: 125.0,
        category: "Business",
        image: "https://www.simplilearn.com/ice9/free_resources_article_thumb/Agile_Project_Management_Methodology.jpg",
        instructor: "Nadia Boukadida",
        rating: 4.9,
        students: 980,
        duration: "7h 45min",
        level: "Intermédiaire",
        discountPercentage: 32,
      ),
    ];
  }
}
