// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRHE_sVlpP0X9K2yDwNnOXfFeOJNzA2Mg',
    appId: '1:933499726809:web:12277936f106d5eb4e47c8',
    messagingSenderId: '933499726809',
    projectId: 'plateforme-educative-2020b',
    authDomain: 'plateforme-educative-2020b.firebaseapp.com',
    storageBucket: 'plateforme-educative-2020b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGBoGyqYE7SKgNxZMEsxraPz18vOGr4zs',
    appId: '1:933499726809:android:f12b68156b804a6e4e47c8',
    messagingSenderId: '933499726809',
    projectId: 'plateforme-educative-2020b',
    storageBucket: 'plateforme-educative-2020b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI4Cd7NHTT4IeO71_zkL2E4z6sFtpnl-4',
    appId: '1:933499726809:ios:b57ba431fcb57ded4e47c8',
    messagingSenderId: '933499726809',
    projectId: 'plateforme-educative-2020b',
    storageBucket: 'plateforme-educative-2020b.firebasestorage.app',
    iosBundleId: 'com.educativeapp.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI4Cd7NHTT4IeO71_zkL2E4z6sFtpnl-4',
    appId: '1:933499726809:ios:b57ba431fcb57ded4e47c8',
    messagingSenderId: '933499726809',
    projectId: 'plateforme-educative-2020b',
    storageBucket: 'plateforme-educative-2020b.firebasestorage.app',
    iosBundleId: 'com.educativeapp.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRHE_sVlpP0X9K2yDwNnOXfFeOJNzA2Mg',
    appId: '1:933499726809:web:9f3ab3b85d56490d4e47c8',
    messagingSenderId: '933499726809',
    projectId: 'plateforme-educative-2020b',
    authDomain: 'plateforme-educative-2020b.firebaseapp.com',
    storageBucket: 'plateforme-educative-2020b.firebasestorage.app',
  );
}
