name: educative_platform
description: Plateforme éducative mobile

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.13.4
  firebase_storage: ^11.5.3
  provider: ^6.1.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true